"use client";

import { useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { MPProfile, MPLADSFund } from "@/lib/types";
import { formatINR, formatPercent } from "@/lib/format";

interface RTITemplateProps {
  mp: MPProfile;
  mplads: MPLADSFund;
}

function generateRTIText(mp: MPProfile, mplads: MPLADSFund): string {
  const today = new Date().toLocaleDateString("en-IN");
  const house = mp.house === "lok_sabha" ? "Lok Sabha" : "Rajya Sabha";
  const fiscalYear = "2024-25";

  let contextNote = "";
  if (mplads.released != null || mplads.expended != null) {
    const parts: string[] = [];
    if (mplads.released != null) parts.push(`Released: ${formatINR(mplads.released)}`);
    if (mplads.expended != null) parts.push(`Expended: ${formatINR(mplads.expended)}`);
    if (mplads.utilization_rate != null) parts.push(`Utilization: ${formatPercent(mplads.utilization_rate)}`);
    contextNote = `\n\n[Note: Publicly available data shows: ${parts.join(", ")}. This RTI seeks to verify and supplement this data.]`;
  }

  return `RIGHT TO INFORMATION APPLICATION
Under Section 6(1) of the Right to Information Act, 2005

Date: ${today}

To,
The Public Information Officer (PIO) / District Magistrate,
Office of the District Magistrate,
${mp.constituency} District,
${mp.state.charAt(0).toUpperCase() + mp.state.slice(1)}

Subject: Information regarding MPLADS Fund utilization under the constituency of
${mp.name}, Member of Parliament (${house}), ${mp.constituency} — FY ${fiscalYear}

Sir/Madam,

I hereby request the following information under the RTI Act, 2005, regarding
MPLADS funds for ${mp.constituency} represented by ${mp.name} (${house}).

INFORMATION SOUGHT:

1. FUND STATEMENTS
   Complete fund statements for FY ${fiscalYear}: opening balance, releases,
   interest earned, expenditure, closing balance, and cumulative totals.

2. SANCTION ORDER COPIES
   All sanction orders for works recommended by the MP during FY ${fiscalYear}.

3. UTILIZATION CERTIFICATES & PAYMENT RECORDS
   All UCs submitted for completed works and payment records to contractors.

4. COMPLETION CERTIFICATES & ASSET HANDOVER
   Completion certificates, asset handover details, and status of in-progress works.

5. AUDIT REPORTS & COMPLIANCE
   Any audit reports on MPLADS works and details of audit objections.

6. DISTRICT LEVEL MONITORING
   Minutes of DLMC meetings and physical inspection reports.

Fee: Rs 10 by IPO/DD/Court Fee Stamp. Response within 30 days.${contextNote}

---
Generated by MP Transparency Tracker`;
}

export function RTITemplate({ mp, mplads }: RTITemplateProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const rtiText = generateRTIText(mp, mplads);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(rtiText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = rtiText;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [rtiText]);

  return (
    <Card>
      <CardHeader
        className="cursor-pointer select-none"
        onClick={() => setIsOpen(!isOpen)}
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="w-7 h-7 flex items-center justify-center border-2 border-ink bg-highlight font-bold font-mono text-sm">
              {isOpen ? "−" : "+"}
            </span>
            <CardTitle>RTI Template for MPLADS Verification</CardTitle>
          </div>
        </div>
      </CardHeader>
      {isOpen && (
        <CardContent>
          <div className="space-y-3">
            <p className="text-sm text-text-secondary">
              Pre-filled RTI application for verifying MPLADS fund data.
              Copy and customize before submission to the District Magistrate.
            </p>
            <div className="flex gap-2">
              <button
                onClick={handleCopy}
                className="border-3 border-ink bg-surface shadow-brutal-sm brutal-press hover:bg-highlight px-3 py-1.5 font-bold uppercase text-ink text-sm"
              >
                {copied ? "Copied!" : "Copy to Clipboard"}
              </button>
            </div>
            <pre className="p-4 border-2 border-ink bg-surface text-xs font-mono whitespace-pre-wrap overflow-x-auto max-h-96 overflow-y-auto">
              {rtiText}
            </pre>
          </div>
        </CardContent>
      )}
    </Card>
  );
}
